name: 'checkout-repo'
description: 'Check out the repository'
inputs:
  project-name:
    description: 'Project name'
    required: true
    default: 'your-repo-name'
runs:
  using: "composite"
  steps:
    - name: checkout
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          mv ${{ inputs.who-to-greet }} ${{ inputs.who-to-greet }}-$(date +%s) > /dev/null
          git clone https://${{ secrets.GIHUB_ACTION_USER }}:${{ secrets.GIHUB_ACTION_TOKEN }}@github.com/datnguye/${{ inputs.who-to-greet }}.git