name: SSH deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    

env:
  project_name: superset-ci-template
  service_name: ${{ secrets.NGINX_SERVICE_NAME }}
  service_port: ${{ secrets.NGINX_SERVICE_PORT }}
  nginx_site_path: ${{ secrets.NGINX_SITE_PATH }}/${{ secrets.NGINX_SERVICE_NAME }}.${{ secrets.DOMAIN }}
  nginx_unit_path: ${{ secrets.NGINX_UNIT_PATH }}/${{ secrets.NGINX_SERVICE_NAME }}.service
  

jobs:
      
  ssh_publish:
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v1

      - name: Run ssh checkout
        uses: ./.github/actions/ssh-checkout
        with:
          project-name: ${{ env.project_name }}
          ssh-host: ${{ secrets.SSH_HOST }}
          ssh-username: ${{ secrets.SSH_USER }}
          ssh-passphrase: ${{ secrets.SSH_PASSPHRASE }}
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          git-user: ${{ secrets.GIHUB_ACTION_USER }}
          git-token: ${{ secrets.GIHUB_ACTION_TOKEN }}

      # - name: install superset
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USER }}
      #     passphrase: ${{ secrets.SSH_PASSPHRASE }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     script: |
      #       cd /root/${{ env.project_name }}
      #       apt-get install build-essential libssl-dev libffi-dev python3-dev python3-pip libsasl2-dev libldap2-dev
      #       python -m pip install virtualenv
      #       python -m venv venv
      #       . venv/bin/activate
      #       python -m pip install apache-superset
      #       python -m pip install Flask-WTF==0.14.2
      #       python -m pip install werkzeug==0.16.1
      #       python -m pip install pillow==8.4.0
      #       superset db upgrade
      #       superset fab create-admin --username ${secrets.SUPERSET_ADMIN_USR} --firstname Dat --lastname Nguyen --email datnguyen.it09@gmail.com --password ${secrets.SUPERSET_ADMIN_PWD}
      #       superset load_examples
      #       superset init

      # - name: make service files
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USER }}
      #     passphrase: ${{ secrets.SSH_PASSPHRASE }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     script: |
      #       echo "[Unit]"                                                             >  ${{ env.nginx_unit_path }}
      #       echo "Description=superset service"                                       >> ${{ env.nginx_unit_path }}
      #       echo "After=multi-user.target"                                            >> ${{ env.nginx_unit_path }}
      #       echo "[Service]"                                                          >> ${{ env.nginx_unit_path }}
      #       echo "Type=simple"                                                        >> ${{ env.nginx_unit_path }}
      #       echo "Restart=always"                                                     >> ${{ env.nginx_unit_path }}
      #       echo "WorkingDirectory=/root/${{ env.project_name }}"                     >> ${{ env.nginx_unit_path }}
      #       echo "VIRTUAL_ENV=/root/${{ env.project_name }}/venv"                     >> ${{ env.nginx_unit_path }}
      #       echo "Enviroment=PATH=\$VIRTUAL_ENV/bin:\$PATH"                           >> ${{ env.nginx_unit_path }}
      #       echo "ExecStart=/root/${{ env.project_name }}/venv/bin/python -m superset run -p ${{ env.service_port }} --with-threads" >> ${{ env.nginx_unit_path }}
      #       echo "[Install]"                                                          >> ${{ env.nginx_unit_path }}
      #       echo "WantedBy=multi-user.target"                                         >> ${{ env.nginx_unit_path }}
      #       #
      #       echo "server {"                                                           >  ${{ env.nginx_site_path }}
      #       echo "  server_name ${{ env.service_name }}.${{ secrets.DOMAIN }};"       >> ${{ env.nginx_site_path }}
      #       echo "  location / {"                                                     >> ${{ env.nginx_site_path }}
      #       echo "    proxy_pass http://127.0.0.1:${{env.service_port}};"             >> ${{ env.nginx_site_path }}
      #       echo "    proxy_set_header Host \$host;"                                  >> ${{ env.nginx_site_path }}
      #       echo "    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;"  >> ${{ env.nginx_site_path }}
      #       echo "    proxy_set_header X-Forwarded-Proto \$scheme;"                   >> ${{ env.nginx_site_path }}
      #       echo "  }"                                                                >> ${{ env.nginx_site_path }}
      #       echo "}"                                                                  >> ${{ env.nginx_site_path }}
      #       #
      #       certbot --nginx -d ${{ env.service_name }}.${{ secrets.DOMAIN }} --non-interactive --agree-tos -m datnguyen.it09@gmail.com

      # - name: start service
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USER }}
      #     passphrase: ${{ secrets.SSH_PASSPHRASE }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     script: |
      #       systemctl enable ${{ env.service_name }}.service
      #       systemctl daemon-reload
      #       systemctl restart ${{ env.service_name }}.service
      #       # systemctl status ${{ env.service_name }}.service